// panel/panel.js
// Side-panel controller for the Optic Chrome extension.
//
// Responsibilities:
//   - On load, read saved state from chrome.storage.local and restore UI.
//   - Wire every interface event: API key save, prompt-helper expand/copy,
//     mode toggle, Visualize, Clear, Export.
//   - Coordinate with service-worker.js to call the Anthropic API.
//
// Security model:
//   - The Anthropic API key lives only in chrome.storage.local and is sent
//     only to the service worker via chrome.runtime.sendMessage. It is never
//     written to the console, never echoed into the DOM as text, never
//     copied to the clipboard, and never persisted anywhere else.
//   - All graph content (nodes, edges, labels — generated by the LLM) is
//     rendered using document.createElement + textContent. innerHTML is not
//     used anywhere in this file, so no string from the model can ever be
//     interpreted as HTML.

// ---------------------------------------------------------------------------
// Storage keys (single source of truth)
// ---------------------------------------------------------------------------

const STORAGE_API_KEY    = 'optic_api_key';
const STORAGE_LAST_GRAPH = 'optic_last_graph';
const STORAGE_VIEW_MODE  = 'optic_view_mode';

// ---------------------------------------------------------------------------
// Prompt text constants
// Each is what the corresponding prompt-option button copies to the user's
// clipboard, ready to paste into whichever AI tool they're using.
// ---------------------------------------------------------------------------

const PROMPTS = {
  coding: `You have access to this project's codebase. Read through it to understand the system, then write a clean architecture description that I'll paste into the Optic visualization tool.

In flowing plain-English prose, cover: the frontend (what the user sees and interacts with), the backend (application logic, services, and internal APIs), the data layer (databases, schemas, anything persisted), external services and integrations (third-party APIs the system depends on), authentication (how users are identified and authorized), any AI services involved (model providers, inference pipelines, embeddings), and how data flows between these components in real use — what calls what, what reads what, what triggers what.

Aim for 150 to 300 words. Do not use bullet points, numbered lists, code blocks, or section headings — just clear paragraph-style prose grounded in what's actually in the codebase. Do not invent components that aren't present.

Going forward, whenever you make a significant architectural change to this project — adding a service, changing how components connect, integrating a new external API, or modifying authentication or data flow — pause and ask me: "This was a significant architectural change. Would you like to refresh your Optic visualization?" If I say yes, produce an updated architecture description in this same format.`,

  general: `I'm going to describe an application I'm building (or have built). I'd like you to produce a clean architecture description I can paste into the Optic visualization tool.

In flowing plain-English prose, cover: the frontend (what the user sees and interacts with), the backend (application logic and services), the data layer (databases and persistence), external services and integrations (third-party APIs), authentication, any AI services involved, and how data flows between these components in real use.

Aim for 150 to 300 words. Do not use bullet points, numbered lists, code blocks, or section headings — just clear paragraph-style prose. Where my description leaves details out, make reasonable assumptions but flag them in the text so I can correct them. If anything important is unclear, ask me one or two clarifying questions before you write the description.

Going forward, whenever I describe a significant change to this system — a new service, a new integration, a change to how components connect, or a shift in authentication or data flow — offer to produce an updated architecture description for Optic in this same format.`,

  refresh: `The project has changed since the last Optic visualization. Please produce a fresh, updated architecture description in the same structured plain-English format as before: 150 to 300 words covering the frontend, backend, data layer, external services, authentication, AI services, and how data flows between these components. No bullet points, no code blocks — just clear prose grounded in what the project actually looks like now.`
};

// ---------------------------------------------------------------------------
// Module state
// ---------------------------------------------------------------------------

let currentGraph = null;       // last successfully parsed graph, or null
let currentMode = 'schematic'; // active view: 'schematic' or 'cinematic'
let copyConfirmTimer = null;   // setTimeout id for the copy confirmation
let saveConfirmTimer = null;   // setTimeout id for the "Saved" button flash

// ---------------------------------------------------------------------------
// Element handles (resolved during init)
// ---------------------------------------------------------------------------

const el = {};

function resolveElements() {
  el.modeSchematic       = document.getElementById('mode-schematic');
  el.modeCinematic       = document.getElementById('mode-cinematic');
  el.apiKeyInput         = document.getElementById('api-key-input');
  el.apiKeySave          = document.getElementById('api-key-save');
  el.promptHelperToggle  = document.getElementById('prompt-helper-toggle');
  el.promptHelperOptions = document.getElementById('prompt-helper-options');
  el.promptOptionCoding  = document.getElementById('prompt-option-coding');
  el.promptOptionGeneral = document.getElementById('prompt-option-general');
  el.promptOptionRefresh = document.getElementById('prompt-option-refresh');
  el.copyConfirmation    = document.getElementById('copy-confirmation');
  el.descriptionInput    = document.getElementById('description-input');
  el.visualizeButton     = document.getElementById('visualize-button');
  el.loadingIndicator    = document.getElementById('loading-indicator');
  el.loadingText         = document.querySelector('#loading-indicator .loading-text');
  el.schematicView       = document.getElementById('schematic-view');
  el.cinematicView       = document.getElementById('cinematic-view');
  el.clearButton         = document.getElementById('clear-button');
  el.exportButton        = document.getElementById('export-button');
}

// ---------------------------------------------------------------------------
// Initialization
// ---------------------------------------------------------------------------

async function init() {
  resolveElements();
  await restoreState();
  wireEvents();
}

async function restoreState() {
  const stored = await chrome.storage.local.get([
    STORAGE_API_KEY,
    STORAGE_LAST_GRAPH,
    STORAGE_VIEW_MODE
  ]);

  // Restore API key (populate input only; never log or echo).
  if (typeof stored[STORAGE_API_KEY] === 'string') {
    el.apiKeyInput.value = stored[STORAGE_API_KEY];
  }

  // Restore view mode (default: schematic).
  const savedMode = stored[STORAGE_VIEW_MODE];
  setMode(savedMode === 'cinematic' ? 'cinematic' : 'schematic');

  // Restore last graph and render it.
  if (stored[STORAGE_LAST_GRAPH] && typeof stored[STORAGE_LAST_GRAPH] === 'object') {
    currentGraph = stored[STORAGE_LAST_GRAPH];
    renderCurrentGraph();
  }
}

function wireEvents() {
  // API key
  el.apiKeySave.addEventListener('click', onApiKeySaveClick);

  // Prompt helper expand/collapse
  el.promptHelperToggle.addEventListener('click', onPromptHelperToggle);

  // Three prompt copy buttons
  el.promptOptionCoding.addEventListener('click',  () => copyPrompt('coding'));
  el.promptOptionGeneral.addEventListener('click', () => copyPrompt('general'));
  el.promptOptionRefresh.addEventListener('click', () => copyPrompt('refresh'));

  // Mode toggle
  el.modeSchematic.addEventListener('click', () => setMode('schematic'));
  el.modeCinematic.addEventListener('click', () => setMode('cinematic'));

  // Primary actions
  el.visualizeButton.addEventListener('click', onVisualizeClick);
  el.clearButton.addEventListener('click', onClearClick);
  el.exportButton.addEventListener('click', onExportClick);
}

// ---------------------------------------------------------------------------
// API key handling
// ---------------------------------------------------------------------------

async function onApiKeySaveClick() {
  const value = el.apiKeyInput.value.trim();
  if (value.length === 0) return;

  // Stored ONLY in chrome.storage.local. Not logged, not echoed elsewhere.
  await chrome.storage.local.set({ [STORAGE_API_KEY]: value });
  flashSaveButton();
}

function flashSaveButton() {
  el.apiKeySave.textContent = 'Saved';
  if (saveConfirmTimer) clearTimeout(saveConfirmTimer);
  saveConfirmTimer = setTimeout(() => {
    el.apiKeySave.textContent = 'Save';
    saveConfirmTimer = null;
  }, 2000);
}

// ---------------------------------------------------------------------------
// Prompt helper expand + copy
// ---------------------------------------------------------------------------

function onPromptHelperToggle() {
  const isNowHidden = el.promptHelperOptions.classList.toggle('hidden');
  el.promptHelperToggle.setAttribute('aria-expanded', String(!isNowHidden));
}

async function copyPrompt(kind) {
  const text = PROMPTS[kind];
  if (typeof text !== 'string') return;
  try {
    await navigator.clipboard.writeText(text);
    showCopyConfirmation();
  } catch (err) {
    // navigator.clipboard.writeText can reject in rare permission scenarios
    // (e.g. document not focused). Surface a quiet notice rather than crash.
    showStatus('Could not copy to clipboard. Please try again.');
  }
}

function showCopyConfirmation() {
  el.copyConfirmation.classList.remove('hidden');
  if (copyConfirmTimer) clearTimeout(copyConfirmTimer);
  copyConfirmTimer = setTimeout(() => {
    el.copyConfirmation.classList.add('hidden');
    copyConfirmTimer = null;
  }, 3000);
}

// ---------------------------------------------------------------------------
// Visualize flow
// ---------------------------------------------------------------------------

async function onVisualizeClick() {
  const description = el.descriptionInput.value.trim();
  if (description.length === 0) {
    showStatus('Paste a system description above first.');
    return;
  }

  // Read the key only at request time. It is not held in any module-level
  // variable; it lives in chrome.storage.local and is fetched on demand.
  const stored = await chrome.storage.local.get([STORAGE_API_KEY]);
  const apiKey = stored[STORAGE_API_KEY];
  if (typeof apiKey !== 'string' || apiKey.length === 0) {
    showStatus('Please save your Anthropic API key above first.');
    return;
  }

  showStatus('Generating visualization…');

  let response;
  try {
    // The API key is passed to the service worker via the runtime message
    // channel — an in-process IPC, not a network call. It does not leave
    // this function in any other form.
    response = await chrome.runtime.sendMessage({
      action: 'parseSystem',
      apiKey,
      description
    });
  } catch (err) {
    const msg = err && err.message ? err.message : String(err);
    showStatus(`Could not reach the service worker: ${msg}`);
    return;
  }

  // Defensive: the response could be missing if the service worker closed
  // the channel without calling sendResponse.
  if (!response || typeof response !== 'object') {
    showStatus('Service worker returned no response.');
    return;
  }

  if (response.ok === true && response.graph) {
    currentGraph = response.graph;
    await chrome.storage.local.set({ [STORAGE_LAST_GRAPH]: currentGraph });
    hideStatus();
    renderCurrentGraph();
  } else {
    const errMsg = typeof response.error === 'string' ? response.error : 'Unknown error.';
    showStatus(`Error: ${errMsg}`);
  }
}

// ---------------------------------------------------------------------------
// TEMPORARY text-based renderer
//
// This is a placeholder so the full pipeline (panel → SW → Anthropic → SW →
// panel) can be exercised end-to-end before the real D3 visualizers exist.
// It will be REPLACED entirely when the schematic + cinematic visualizers
// are built. Anything inside renderGraphAsText is throwaway.
// ---------------------------------------------------------------------------

function renderCurrentGraph() {
  if (!currentGraph) return;
  const active   = currentMode === 'cinematic' ? el.cinematicView : el.schematicView;
  const inactive = currentMode === 'cinematic' ? el.schematicView : el.cinematicView;
  renderGraphAsText(currentGraph, active);
  inactive.replaceChildren(); // avoid stale rendering in the hidden container
}

function renderGraphAsText(graph, container) {
  container.replaceChildren();

  // Inline-styled wrapper so the placeholder is actually readable inside
  // the .viz-container (which is overflow:hidden by design). Goes away
  // entirely with the real visualizers.
  const wrapper = document.createElement('div');
  wrapper.style.padding = '12px';
  wrapper.style.overflowY = 'auto';
  wrapper.style.height = '100%';
  wrapper.style.boxSizing = 'border-box';

  const nodes = Array.isArray(graph.nodes) ? graph.nodes : [];
  const edges = Array.isArray(graph.edges) ? graph.edges : [];

  const nodesHeader = document.createElement('h3');
  nodesHeader.textContent = `Nodes (${nodes.length})`;
  wrapper.appendChild(nodesHeader);

  const nodesList = document.createElement('ul');
  for (const node of nodes) {
    const li = document.createElement('li');
    // textContent — string treated as inert text, never as HTML.
    li.textContent = `${node.label} — ${node.type}`;
    nodesList.appendChild(li);
  }
  wrapper.appendChild(nodesList);

  const edgesHeader = document.createElement('h3');
  edgesHeader.textContent = `Edges (${edges.length})`;
  wrapper.appendChild(edgesHeader);

  const edgesList = document.createElement('ul');
  for (const edge of edges) {
    const li = document.createElement('li');
    li.textContent = `${edge.source} → ${edge.target}: ${edge.label}`;
    edgesList.appendChild(li);
  }
  wrapper.appendChild(edgesList);

  container.appendChild(wrapper);
}

// ---------------------------------------------------------------------------
// Mode toggle
// ---------------------------------------------------------------------------

function setMode(mode) {
  if (mode !== 'schematic' && mode !== 'cinematic') return;
  currentMode = mode;

  // Update visual + ARIA state on both toggle buttons.
  el.modeSchematic.classList.toggle('is-active', mode === 'schematic');
  el.modeCinematic.classList.toggle('is-active', mode === 'cinematic');
  el.modeSchematic.setAttribute('aria-selected', mode === 'schematic' ? 'true' : 'false');
  el.modeCinematic.setAttribute('aria-selected', mode === 'cinematic' ? 'true' : 'false');

  // Show the active view container, hide the other.
  el.schematicView.classList.toggle('hidden', mode !== 'schematic');
  el.cinematicView.classList.toggle('hidden', mode !== 'cinematic');

  // Persist the choice (fire-and-forget — no awaiting needed).
  chrome.storage.local.set({ [STORAGE_VIEW_MODE]: mode });

  // Re-render the current graph in the newly active view, if any.
  if (currentGraph) renderCurrentGraph();
}

// ---------------------------------------------------------------------------
// Clear / Export
// ---------------------------------------------------------------------------

async function onClearClick() {
  el.descriptionInput.value = '';
  currentGraph = null;
  el.schematicView.replaceChildren();
  el.cinematicView.replaceChildren();
  await chrome.storage.local.remove(STORAGE_LAST_GRAPH);
  hideStatus();
}

function onExportClick() {
  if (!currentGraph) {
    showStatus('Nothing to export yet — generate a visualization first.');
    return;
  }

  // Build a JSON blob and trigger a download via a temporary anchor. The
  // blob URL is created locally (blob:chrome-extension://…) and never hits
  // the network; it is revoked immediately after the click to free memory.
  const json = JSON.stringify(currentGraph, null, 2);
  const blob = new Blob([json], { type: 'application/json' });
  const url  = URL.createObjectURL(blob);

  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = 'optic-graph.json';
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}

// ---------------------------------------------------------------------------
// Status / loading-indicator helpers
// (The loading-indicator div doubles as a general status message area:
// "Generating…", error messages, empty-input hints, etc.)
// ---------------------------------------------------------------------------

function showStatus(text) {
  if (el.loadingText) {
    el.loadingText.textContent = text;
  } else {
    el.loadingIndicator.textContent = text;
  }
  el.loadingIndicator.classList.remove('hidden');
}

function hideStatus() {
  el.loadingIndicator.classList.add('hidden');
}

// ---------------------------------------------------------------------------
// Boot
// ---------------------------------------------------------------------------

init().catch((err) => {
  // Catastrophic init failure (DOM not as expected, storage unavailable,
  // etc.). Log to the panel's own devtools console so the developer can
  // diagnose. Even if init read the API key from storage before throwing,
  // the key lives in a local variable inside restoreState() and is not
  // captured in `err.message` or `err.stack` — JS errors do not embed
  // surrounding variable values.
  console.error('[Optic panel] Initialization failed:', err);
});
